batch_size: 64
height: 32
learning_rate: 0.002
max_text_length: 50
model_path: ./Models/
train_epochs: 200
vocab: " '(),-.012345679:ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz\xC1\xC2\
  \xC3\xC7\xC9\xCA\xCD\xD3\xD4\xD5\xDA\xE1\xE3\xE7\xE9\xEA\xF3"
width: 128
